#这个配置文件是用来修改默认设置

spring:
  datasource:
    username: root
    password: tdw970709
    url: jdbc:mysql://localhost:3306/photograph?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
#国际化资源
  messages:
    basename: i18n/index/index
#禁用模板引擎缓存
  thymeleaf:
    cache: false
  session:
    store-type: none
#设置上传文件大小限制
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.tdw.photograph.bean